### ISSUE TITLE
Move pose frame proposal to actual docs

### ISSUE THREAD

**Issue by EricCousineau-TRI** [osrf/sdf_tutorials#16]
At present (cf72a5a), it's still in "Proposals".

**Comment by scpeters** [comment]
I've started looking at this, since we'll need to update the parsing stages for model composition in SDFormat 1.8, but those aren't in documentation form yet.

I think the content of the pose frame proposal  used for SDFormat 1.7 can live as a versioned sibling of the [SDFormat 1.5 Pose Frame Semantics documentation](http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.5), which is marked as Advanced.

But I think we should also add an SDFormat 1.7 version to the [Beginner model kinematics tutorial](http://sdformat.org/tutorials?tut=spec_model_kinematics&cat=specification&) that describes the new way that model kinematics can be defined with `//frame`, `//pose/@relative_to`, and `//joint/axis/@expressed_in`. I'll create a new issue for that.

**Comment by scpeters** [comment]
I created https://github.com/osrf/sdf_tutorials/issues/20 regarding a 1.7 version of the model kinematics tutorial.

**Comment by scpeters** [comment]
starting work in [branch proposal_to_documentation](https://github.com/osrf/sdf_tutorials/compare/proposal_to_documentation?expand=1). I've copied the proposal into a sibling of the current documentation, as discussed above, and rephrased the introduction, but the rest of it is written like a proposal, so that needs to be updated.

preview:

* http://sdformat.org/tutorials?branch=proposal_to_documentation
* 1.5: http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.5&cat=specification&branch=proposal_to_documentation
* 1.7: http://sdformat.org/tutorials?tut=pose_frame_semantics&ver=1.7&cat=specification&branch=proposal_to_documentation

**Comment by EricCousineau-TRI** [comment]
(Reassigning given #49)

**Comment by azeey** [comment]
If this issue is about creating a frames semantics tutorial, as opposed to moving the proposal to docs, should the title be updated?
